### ISSUE TITLE
host.py: error: unrecognized arguments: > cli_out.txt

### ISSUE THREAD

**Issue by nerdyrodent** [NotNANtoN/AuViMi#1]
Hi,

When trying to run locally like this:

`python app.py --run_local=1 --host=localhost --python_path=/home/nerdy/anaconda3/envs/auvimi/bin/python --mode=pic --size=512 --text="An ugly human with a face like the back end of a bulldog"`

The following error is produced:

> usage: host.py [-h] [--gen_backbone {deepdaze,bigsleep}] [--size SIZE]
>                [--epochs EPOCHS]
>                [--gradient_accumulate_every GRADIENT_ACCUMULATE_EVERY]
>                [--batch_size BATCH_SIZE] [--lr LR] [--num_layers NUM_LAYERS]
>                [--saturate_bound SATURATE_BOUND]
>                [--lower_bound_cutout LOWER_BOUND_CUTOUT]
>                [--do_occlusion DO_OCCLUSION] [--center_bias CENTER_BIAS]
>                [--center_focus CENTER_FOCUS] [--meta META] [--meta_lr META_LR]
>                [--opt_steps OPT_STEPS] [--text TEXT]
>                [--text_weight TEXT_WEIGHT] [--run_avg RUN_AVG]
>                [--run_local RUN_LOCAL] [--python_path PYTHON_PATH]
>                [--host HOST] [--user USER] [--mode {stream,pic}]
> host.py: error: unrecognized arguments: > cli_out.txt
> ^CTraceback (most recent call last):
>   File "/home/nerdy/github/AuViMi/app.py", line 220, in <module>
>     host_process = main(host, user, args)
>   File "/home/nerdy/github/AuViMi/app.py", line 139, in main
>     key = cv2.waitKey(1)
> KeyboardInterrupt

**Comment by NotNANtoN** [comment]
Hi,

thank your for your interest in this project and the first issue! 

I just pushed a fix for your issue, now that should work. Unfortunately, I cannot debug the actual training process of run_local, as I do not have a single machine with a GPU and a webcam. So, let me know if other issues arise.

By the way, you do not need to define `host` when using run_local.

I'm curious to see if you get any results with your prompt ;)
